config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'pages/bookings', to: 'pages#bookings'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :hotels, only: %i[index show]
  resources :rooms, only: %i[index show] do
    resources :bookings, only: %i[create edit update]
  end

  resources :bookings, only: %i[destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :starts_at, :ends_at, presence: true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy

  validates :name, :address, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy

  validates :capacity, :price_per_night, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :select_room, only: %i[new create edit]
  before_action :select_booking, only: %i[edit update destroy]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.room = @room
    @booking.user = current_user
    if @booking.save
      redirect_to room_path(@room), notice: "Succesfully booked!"
    else
      render 'rooms/show', status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to pages_dashboard_path
  end

  private

  def select_room
    @room = Room.find(params[:room_id])
  end

  def select_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @rooms = Room.all
    @rooms = Room.order(price_per_night: :asc)
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hotels/_hotelcards.html.erb
<div class="card">
    <%= link_to hotel_path(hotel), class: 'text-decoration-none' do %>
      <div style="max-width: 100%; object-fit: cover;
              width: 350; height: 200px;
              overflow: hidden; align-items: center; display: flex; justify-content: center; align-items: center;">
        <% if hotel.photo.attached?  %>
            <%= image_tag(hotel.photo, :width => 350, :height => 350, crop: :fit) %>
        <% else %>
          <%= image_tag('hotel.jpeg', :height => 250) %>
        <% end %>
      </div>

      <h3><%= hotel.name %></h3>
    <% end %>
  </div>

app/views/hotels/index.html.erb
<div class="row justify-content-center">
    <div class="col-sm-8">
      <div class="row justify-content-center cardcontainer">
        <% if @hotels.any? %>
          <% @hotels.each do |hotel| %>
            <%= render "hotelcards", hotel: hotel %>
          <% end %>
        <% else %>
          <em>Sorry, no hotels found.</em>
        <% end %>
      </div>
    </div>
  </div>

app/views/hotels/show.html.erb
<h1><%= @hotel.name %></h1>
<p><%= @hotel.description %></p>


<% @hotel.rooms.each do |room| %>
  <%= render partial: 'rooms/roomcard', locals: { room: room } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookRoomsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;700&display=swap" rel="stylesheet">


  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/bookings.html.erb
<h2>My bookings</h2>
<% if current_user.bookings.nil? %>
  <p><%= "No bookings yet!" %></p>
<% else %>
  <div class="cardcontainer">
    <% current_user.bookings.each do |booking| %>
      <div class="card">
        <%= booking.room.hotel.name %>
        <%= image_tag(booking.room.hotel.photo) %>
        <h3>Arrival date: <%= booking.starts_at.strftime("%A %e %B") %></h3>
        <h3>Departure date: <%= booking.ends_at.strftime("%A %e %B") %></h3>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<section class="page-1">
<div class="h1container">
  <h1>Hoteleria</h1>
</div>
  <article>
    <div class="div__slide">
      <%= link_to 'Check hotels', hotels_path, class: 'text-decoration-none' %></h2>
    </div>
  </article>
  <div class="parallax"></div>
</section>
<section class="page-2">
  <article>
    <div class="div__slide">
      <%= link_to 'Check rooms', rooms_path, class: 'text-decoration-none' %>
    </div>
  </article>
  <div class="parallax"></div>
  <div class="parallax"></div>
</section>

app/views/rooms/_booking_form.html.erb
<div class="modal fade" id="exampleModal" tabindex="2" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 1800;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><i class="fa-solid fa-map-location-dot"></i> </i>Book</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <div class="col-6 mb-3 form-inline justify-content-center" data-controller="datepicker"

      data-datepicker-price-value="<%= @room.price_per_night.to_json %>">

    <%= simple_form_for ([ @room, @booking]) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.input :starts_at, as: :string, input_html: { data: { datepicker_target: "start", action: "change->datepicker#startDateInput" } } %>
      <%= f.input :ends_at, as: :string, input_html: { data: { datepicker_target: "end", action: "change->datepicker#endDateInput" } } %>

      <div class="d-flex col-9 justify-content-between flex-grow-1">
        <p> Total price:  </p>
        <strong data-datepicker-target="price"></strong>
      </div>

      <div class="col-9 d-flex justify-content-center" >
        <%= f.submit "Let's go!", class: "btn btn-primary", disabled: true, data: { datepicker_target: "confirm" } %>
      </div>
    <% end %>
  </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/_roomcards.html.erb
<div class="card">
  <%= link_to room_path(room), class: 'text-decoration-none' do %>
    <div style="max-width: 100%; object-fit: cover;
            width: 350; height: 200px;
            overflow: hidden; align-items: center; display: flex; justify-content: center; align-items: center;">
      <% if room.hotel.photo.attached?  %>
          <%= image_tag(room.hotel.photo, :width => 350, :height => 350, crop: :fit) %>
      <% else %>
        <%= image_tag('hotel.jpeg', :height => 250) %>
      <% end %>
    </div>
    <div class="cardinfo">
      <h3 id="hotelname"><%= room.hotel.name %></h3>
        <div class="flex-container space-between">
          <h3><i class="fa-solid fa-user"></i><%= room.capacity %></h3>
          <h3><%= room.price_per_night %>$ per night</h3>
        </div>
    </div>
  <% end %>
</div>

app/views/rooms/_showcard.html.erb
<div class="showcard">
  <div class="showcardtitle">
    <h2> <%= @room.hotel.name %></h2>
  </div>
 <div class="imgcontainer">
    <%= image_tag(@room.hotel.photo) %>
  </div>
  <div class="showcarddeets">
    <div class="flex space-between">
      <h3><i class="fa-solid fa-user"></i><%= @room.capacity %></h3>
      <h3><%= @room.price_per_night %>$ per night</h3>
    </div>
    <h3><%= @room.hotel.description %></h3>
  </div>
  <button class="btn btn-primary sub-nav-item m-0" id="add-new" data-bs-toggle="modal" data-bs-target="#exampleModal">Book</button>

  <% if user_signed_in? %>
    <%= render "/rooms/booking_form"%>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="row justify-content-center">
    <div class="col-sm-8">
      <div class="row justify-content-center cardcontainer">
        <% if @rooms.any? %>
          <% @rooms.each do |room| %>
            <div>
              <%= render "roomcards", room: room %>
            </div>
          <% end %>
        <% else %>
          <em>Sorry, no rooms found.</em>
        <% end %>
      </div>
    </div>
  </div>

app/views/rooms/show.html.erb
<div class= "container">
  <%= render "showcard" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My bookings", pages_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>